name = "openapi-auth"
main = "src/index.ts"
compatibility_date = "2024-02-08"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "dev-openapi-auth"
database_id = "a52efb6f-e6e5-4e00-8d73-4b42022a1d0e"