name = "openapi-auth"
main = "src/index.ts"
compatibility_date = "2024-02-08"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "auth-playground"
database_id = "636fd0b1-316d-4ca3-8ca0-3181e706844a"
